version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: yarn add dependencies
          command: | 
            yarn add -save
      - run: 
          name: build app
          command: | 
            yarn build     
      - run:
          name: run app
          command: | 
            yarn dev
Workflows:
  build:
    jobs:
       - build
