version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: yarn add dependencies
          command: | 
            yarn add
      - run:
          name: run app
          command: | 
            yarn dev
Workflows:
  build:
    jobs:
       - build
